### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by jefflembeck** [npm/captain-hook#12]
Currently, working on captain hook largely would be  nicer if we had a web interface that gives us a CRUD api for what we keep in the DB

Access said API, at this point, is wired up as an express app (see: https://github.com/npm/captain-hook/blob/master/src/lib/api.js)

Express is a pretty good solution for this (though we could keep restify around for consistency).

General things needed:

Something to handle views.
Something to handle deployment of both apps at once (likely another port)

MORE STUFF WHEN I REMEMBER TO COME BACK TO THIS ISSUE LATER

**Comment by ashleygwilliams** [comment]
hey! so #18 should solve this (if we are happy with an express solution), though a couple of things...

> Something to handle views.
i'd rather do this in another repo. ideally on the npm website...
