### ISSUE TITLE
Not found: `@npmcorp/npm-hook-receiver`

### ISSUE THREAD

**Issue by gnerkus** [npm/captain-hook#17]
I received this error message when I executed `npm install` in the project's directory:

> Not found : @npmcorp/npm-hook-receiver

I checked the status of the module on npmjs.org and realised it hasn't been downloaded yet.

Does this mean it hasn't been made public yet?

**Comment by ashleygwilliams** [comment]
whoops! it's a private package rn, will publish that publicly and you should be all set! sorry about that- and thanks for filing!
